# Generated by Django 4.1.1 on 2022-09-19 20:43

import dj_kaos_utils.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            bases=(dj_kaos_utils.models.mixins.HasAutoFields, models.Model),
        ),
    ]
