# Generated by Django 4.1.1 on 2022-09-19 20:51

import dj_kaos_utils.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', dj_kaos_utils.models.fields.MoneyField()),
                ('code_id', dj_kaos_utils.models.fields.LowerCaseCharField(max_length=255)),
            ],
        ),
    ]
