# Generated by Django 4.1.1 on 2022-12-10 23:42

import dj_kaos_utils.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0003_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', dj_kaos_utils.models.fields.MoneyField()),
                ('code_id', dj_kaos_utils.models.fields.LowerCaseCharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products2', to='simple.category')),
            ],
        ),
    ]
